language: python

python:  
  - "3.6"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-lora
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l      
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      VERSIONIST=true

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/agile-ci-functions.sh)
  - docker_upgrade
  - cache_load
  - bootstrap
  - echo "Tagging the build with tag - $DOCKER_TAG"

script:
  - docker_build_if_needed
  - cache_save

after_success:
  - docker_push_if_needed
  - versionist_if_needed

install:
  - pip install -r travis-deps.txt    

script: python -m unittest discover -v --start-directory test/ --pattern unit*.py