language: python

python:  
  - "3.2"

install:
  - pip install -r travis-deps.txt  
  - pip install -r requirements.txt  

script: python -m unittest discover -v --start-directory test/ --pattern unit*.py