version: '2.1'

services:
  agile-lora:
    container_name: agile-lora
    # image: agile-lora
    build: .
    # depends_on:
    #   - agile-dbus
    #   - agile-core
    volumes:
      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
    restart: always
    privileged: true
    network_mode: "host"